### ISSUE TITLE
PDF在线打开有问题，麻烦处理一下

### ISSUE THREAD

**Issue by yoorxee** [CZHIC/GoViewFIle#1]
![image](https://user-images.githubusercontent.com/3423877/141232007-2fd0ee73-f0a6-4415-92e9-1c509af673b0.png)

**Comment by CZHIC** [comment]
麻烦详细描述下是怎样遇到这个问题的

**Comment by yoorxee** [comment]
URL：http://39.97.98.75:8082/view/upload

截图中，111.pdf 是我上传的，普通预览、PDF预览均无法使用

![image](https://user-images.githubusercontent.com/3423877/141236432-131b4c01-9e7a-4323-a9a7-7c17ad645af0.png)

**Comment by CZHIC** [comment]
已修复
