### ISSUE TITLE
你好，帮我看下把，打不开

### ISSUE THREAD

**Issue by xp12047** [CZHIC/GoViewFIle#4]
![Screenshot_20220607_154131_com termux](https://user-images.githubusercontent.com/56335408/172325362-7cbb899f-7ead-4820-8ff4-069bde9ff4a4.jpg)
我手机上用termux编译试了下，报错

**Comment by CZHIC** [comment]
报错很明显呀，mkdir创建目录失败，需要给对应目录增加写权限

**Comment by xp12047** [comment]
写入权限应该怎么增加？
